### ISSUE TITLE
Outdated API

### ISSUE THREAD

**Issue by lcsdavid** [JuniorJPDJ/messenger_api#10]
README.md example returns following trace:

Traceback (most recent call last):
  File "facebook.py", line 32, in <module>
    me = Messenger(login, password)
  File "/home/<user>/.local/lib/python3.8/site-packages/messenger_api/Messenger.py", line 30, in __init__
    self._parse_threadlist(self.msgapi.mercury_payload)
  File "/home/<user>/.local/lib/python3.8/site-packages/messenger_api/Messenger.py", line 47, in _parse_threadlist
    for t in threadlist['ordered_threadlists'][0]['thread_ids']:
KeyError: 'ordered_threadlists'

Overall, it seems that this API is now outdated.

**Comment by JuniorJPDJ** [comment]
It is unmaintained like 3 years :/
I saw better alternatives like fbchat-asyncio and similar.
You should give it a try :)
Maybe I'll get some free time in the future, but now I don't have it.
